### PR TITLE
Fixed an issue where the module would not load in DNN9.4.x

### LINKED ISSUE #38: Critical error in DNN 09.04.01
## Describe the bug
Critical error in DNN 09.04.01

## Software Versions
- DNN: 09.04.01
- Module: 07.02.01

## To Reproduce
1. Install module in DNN 09.04.01
2. Add module to a page
3. See error in **Manage > Admin Logs**

## Screenshots
n/a

## Error log
```
10/08/2019 01:35:07
Page Load Exception
host 
DNN 09.04.01 
AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:d6555b79-f859-4ad2-aa0b-01feebc2c789

AssemblyVersion:9.4.1

PortalId:0

UserId:1

TabId:33

RawUrl:/Announcements

Referrer:http://dnn941.loc/Default.aspx?tabid=33&amp;error=Invalid+column+name+%27UrlTrackingInfo%27.&amp;content=0

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36

ExceptionHash:zGupxnx/h59tkwJv07YNxqtDN3Y=

Message:Invalid column name 'UrlTrackingInfo'.

StackTrace:

InnerMessage:Invalid column name 'UrlTrackingInfo'.

InnerStackTrace:

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at PetaPoco.Database.<ExecuteReader>d__149`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at DotNetNuke.Modules.Announcements.Components.Business.AnnouncementsController.GetCurrentAnnouncements(Int32 moduleId, DateTime startDate)
   at DotNetNuke.Modules.Announcements.MVP.Presenters.AnnouncementsViewPresenter.GetAnnouncements(Object sender, EventArgs e)
   at DotNetNuke.Modules.Announcements.AnnouncementsView.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:
```

## Additional context
n/a

### PR DESCRIPTION
**Pull request by SCullman**
## Changes made
* Adds Attribute [IgnoreColumn] as suggested by @valadas 

## PR Template Checklist

- [x] Fixes Bug
- [ ] Feature solution
- [ ] Other

## Please mark which issue is solved
Close #38

### CODE REVIEW

**Comment by valadas** [comment]
> Hmm... I don't have this directory or file Components/Business/AnnouncementInfo.cs

This is in the source code only not distributed with the install zip.

**Comment by Ceten** [comment]
Any news on this and a new release?

**Comment by valadas** [comment]
@erikvb @jncraig any plans on publishing a new release soon?

**Comment by jncraig** [comment]
Not sure how my name got associated with this project.  I’d be happy to
help but I’ll need some education.

**Comment by valadas** [comment]
Well, you are listed as an official maintainer :) If you do want it, I would be happy to meet with you to do this together. If not also let me know to remove your name from there...

**Comment by jncraig** [comment]
Daniel,

Sure!  I guess I somehow semi0volunteered sometime back, but that was all.

When would be a good time for you?

Also, what should I do to get prepared.  I am a complete GitNovice ...

**Comment by valadas** [comment]
I am on slack whenever I am on the computer (a lot), just ping me up there and we can meet...

**Pull request merged**
