### PR TITLE
Added test for use cases when the module setting descriptionLength is not set

### LINKED ISSUE #68: Search indexer failed when settings are not set
## Describe the bug
The module content is not indexed

## Software Versions
- DNN: occurs in 09.06.02 and in 09.10.02
- Module: 07.02.05

## To Reproduce
1. Install the module DNN.Announcements v7.2.5 in a recent version of DNN
2. Add an announcement
3. You can see that indexing task will encounter the following error when indexing the module content: Object reference not set to an instance of an object.
4. You cannot find the module content by the search skin object.

## Expected behavior
The module indexation should works by default.

## Error log

AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:8688aeff-f986-4934-917b-cccc4dc458ac
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:BqTbKP2j3169f/omuSJ5tU2iMwI=
Message:Object reference not set to an instance of an object.
StackTrace:
   at DotNetNuke.Modules.Announcements.Components.Business.AnnouncementsController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDateUtc) in D:\Developpement\Tests DNN\DNN9.10.2\Website\DesktopModules\DNN.Announcements\Components\Business\AnnouncementsController.cs:line 281
   at DotNetNuke.Services.Search.ModuleIndexer.IndexSearchDocuments(Int32 portalId, ScheduleHistoryItem schedule, DateTime startDateLocal, Action`1 indexer)
InnerMessage:
InnerStackTrace:
Source:DotNetNuke.Modules.Announcements
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: aricie-lyon-01

## Additional context
I added the module on a page without configuring the module settings.

### PR DESCRIPTION
**Pull request by stetard**
### Description of PR...
Fixed the module content indexing when module settings are not set

## Changes made
- Added test for use cases when the module setting descriptionLength is not set

## PR Template Checklist

- [x] Fixes Bug
- [ ] Feature solution
- [ ] Other

## Please mark which issue is solved
Close #68

### CODE REVIEW

**Comment by WillStrohl** [comment]
This looks great! 

I have two comments/concerns.  Maybe you're already coordinating with @david-poindexter  or @valadas  on this, but here it goes...  

The minimum required version of DNN Platform jumps from 8.0.0 to 9.10.0 in this update.  Do we want to jump up that high?  Should it be to something like DNN 9.6 or 9.8 first?  Just a question... 

Next, you've raised the Newtonsoft.Json dependency to 13 and not 10, which is what is the default in DNN Platform 09.10.00, which you are now targeting.  Do you have a code-related reason to go past what's in the core of DNN?  This isn't a deal-breaker, of course.  It should, however, be a deliberate decision.  

Thank you so much for this hard work!  The community appreciates it!

**Comment by stetard** [comment]
Hello Will
It wasn't so hard that you can think even if it's my first attempt to contribute to an open source project on github.
Regarding the packages upgrade, I was probably in trouble due to the usage of github instead of our usual TFS server.
It might not be a good idea to increase the minimum version for DNN and Newtosoft. I believe that I've seen that it's a good practice to upgrade the nugget packages before working on the code. Moreover I believe that I seen a pull request on the DNN Platform with the upgrade of Newtonsoft to the version 13 a few days ago.
I just wanted to solve an indexing issue we have on some customers old websites we're hosting.

**Comment by valadas** [comment]
Regarding Newtosoft.Json, it can be done before DNN but it needs to be declared in the manifest assembly node with it's version for DNN to generate the proper binding redirects. However, your mileage may vary if other extensions do not work fine with v13. DNN does just fine though.

**Comment by stetard** [comment]
Do you want I downgrade those references? Maybe Newtonsoft to version 10 and dnn to version 9.6 or 9.8 like Will has suggested.
I yes, do I have to do it in a new pull request or is there another way to do that?

**Comment by valadas** [comment]
You can push additional commits to your branch which will update this PR. Now in the future I would advice to create a new branch before doing a PR, cause now you can't do anything on your development branch until this PR gets merged.

**Comment by stetard** [comment]
I viewed your videos which are related to GitHub but I probably missed something.
This morning I tried to add a new commit to my pull request but I'm not sure if it worked. I think that my push is linked to the PR #67 but I didn't choose it in Visual Studio.
I'm staying at your disposal if you need.
Best regards

**Comment by valadas** [comment]
So you are pushing changes to your development branch and any PR based on the branch will receive your changes. In a perfect world you should create a new branch to isolate your changes first.

**Comment by WillStrohl** [comment]
I'll always defer to a consensus unless something is obviously wrong, but I think this update would be best accepted if the Newtson version is lowered to what's in the same version of DNN.  That is, again, unless there's a technical reason to not do that.  

If you're open to it, then I'd suggest opening the solution, making the update, then pushing it again.  (Your previous commit to the same PR does appear to be in the PR history, by the way.) Once the PR is merged, then your source code will be safe again for the Announcements module.  But, until then, you shouldn't touch it again.  :)

**Comment by valadas** [comment]
I don't disagree on bumping Newtonsoft.Json as long as it is properly declared in the manifest assembly node. DNN 9.11 already uses the latest version and for older DNN version it will bump it in a way that _should_  just work, there has been new and improved features as well as deprecation notices, but I have seen no breaking change from 10.0.3 to 13.0.1 versions.

And since there was security issues with the older versions I am all for it.

**Comment by stetard** [comment]
Thanks to Daniel and Will for the feedbacks.
I think I made some mistakes when I pushed my changes. This PR seems to be identified like a change on my development branch. But the PR #67 is coming from the specific branch which I created to isolate the changes. Could you confirm?
At the end I already pushed the go back to the old Newtonsoft version in the PR #67.
Even if my 2 PR don't really respect the good practices, is it possible for you to merge my 2 PR to retrieve a good situation?

**Pull request merged**
